VERSION 0.8

ARG --global supported_ros_platforms = almalinux:8 almalinux:9 almalinux:10

rpmbuild:
  FROM almalinux:8
  RUN dnf install -y rpmdevtools rpmlint

BUILD_PACKAGE:
  FUNCTION
  ARG package
  WORKDIR /tmp/$package
  COPY . /tmp/$package
  RUN rpmbuild -ba ${package}.spec --define "_topdir /tmp/$package/rpm" --define "_sourcedir /tmp/$package"
  RUN rpmlint /tmp/$package/rpm/RPMS/noarch/${package}*.rpm /tmp/$package/rpm/SRPMS/${package}*.src.rpm
  SAVE ARTIFACT /tmp/$package/rpm/RPMS/noarch/${package}*.rpm AS LOCAL output/
  SAVE ARTIFACT /tmp/$package/rpm/SRPMS/${package}*.src.rpm AS LOCAL output/


INSTALL_PACKAGE: 
  FUNCTION
  ARG --required package
  ARG --required distro
  # RUN dnf install -y dnf-command\(config-manager\) && dnf config-manager --set-enabled powertools && dnf install -y epel-release
  COPY (+ros2-release/${package}*.noarch.rpm --distro=${distro}) ./ 
  RUN dnf install -y ${package}*.rpm 


ros2-release:
  ARG --required distro
  FROM +rpmbuild
  DO +BUILD_PACKAGE --package=ros2-release --distro=${distro}
  DO +BUILD_PACKAGE --package=ros2-testing-release --distro=${distro}


build-all:
  FROM almalinux:8
  FOR distro IN $supported_ros_platforms
        BUILD  +ros2-release --distro=${distro} 
  END


test-release-pkg-install:
  # Test that ros-release package is installable and that it configures the necessary files
  ARG distro = almalinux:8
  ARG repo = ros2
  LET package = ${repo}-release
  FROM ${distro}
  DO +INSTALL_PACKAGE --package=${package} --distro=${distro}
  RUN if  [ -f /etc/yum.repos.d/${repo}.repo ] && \ 
          [ -e /etc/yum.repos.d/${repo}.repo ] && \ 
          [ -s /etc/yum.repos.d/${repo}.repo \
  ]; then exit 0; else exit 1; fi;
  RUN if  [ -f /etc/pki/rpm-gpg/ros2-key.gpg ] && \ 
          [ -e /etc/pki/rpm-gpg/ros2-key.gpg ] && \ 
          [ -s /etc/pki/rpm-gpg/ros2-key.gpg \
  ]; then exit 0; else exit 1; fi;

ros2-test-repos:
  # Test that repo configuration is complete when installing keyring and apt-source packages. 
  ARG distro = almalinux:8
  ARG repo = ros2
  LET package = ${repo}-release
  FROM ${distro}
  DO +INSTALL_PACKAGE --package=${package} --distro=${distro}
  RUN dnf makecache -y
  RUN dnf install -y ros-rolling-ros-workspace


integration-check-switch: 
  # Test users are expected to be able to switch between the testing and main repositories seamlessly. 
  ARG distro = almalinux:8
  FROM ${distro}
  DO +INSTALL_PACKAGE --package=ros2-release --distro=${distro}
  RUN dnf makecache -y
  RUN dnf repolist | grep "ros2 "
  RUN dnf remove ros2-release -y
  DO +INSTALL_PACKAGE --package=ros2-testing-release --distro=${distro} 
  RUN dnf makecache -y
  RUN dnf repolist | grep ros2-testing
  # # Verify that main repo is not configured anymore
  RUN if ! dnf repolist | grep "ros2 " ; then exit 0; else exit 1; fi;
